export const COMPANY_CEO="Mrityunjaya";
export const COMPANY_EMAIL="contact@restrohub.com";
export const COMPANY_LOCATION="Hydrabad";
export const COMPANY_NAME="RestroHub";
export const COMPANY_NUMBER="+1 5589 55488 55";
export const DOB_RANGE_MESSAGE="Date of birth should be between January 1, 1930, and today's date. Please enter a valid date.";
export const ENTER_VALID_DATA="Invalid past data";
export const ERROR="error";
export const ERROR_DOUBLE_SPACE="Only one space between words.";
export const ERROR_LEADING_OR_TRAILING_SPACE="Don't start or end with a space or special character.";
export const ERROR_MAXIMUM_LENGTH=(length)=>`Max length: ${length} characters.`;
export const ERROR_MINIMUM_LENGTH=(length)=>`Min length: ${length} characters.`;
export const ERROR_MUST_LENGTH=(length)=>`Length must be: ${length} characters.`;
export const ERROR_PASTE_DATA="Pasted data is invalid.";
export const ERROR_REQUIRED=(label)=>`${label??"This field"} is required.`;
export const ERROR_ALL_REQUIRED="All fields required"
export const ERROR_VALIDATE_EMAIL="Email validation error.";
export const EXPIRATION_TIME=50*60*1000;
export const FALSE="false";
export const NOT_FOUND="Not Found";
export const OPPS_ERROR="There was an issue while processing your request. Please try again later.";
export const OPPS_MSG="Oops!";
export const PASSWORD_NOT_METCH="Passwords do not match.";
export const PASSWORD_STRENGTH="Password must contain at least 8 characters including one uppercase letter, one lowercase letter, one number, and one special character (such as @$!%*?&).";
export const RESTAURANT_ESTABLISHED_YEAR=2020;
export const SERVER_ERROR="Failed to reach server. Please try again later.";
export const SESSION_EXPIRE="Your session has been expire";
export const SOCIAL_MEDIA_LINKS={facebook:"https://facebook.com",instagram:"https://instagram.com",twitter:"https://twitter.com",linkedin:"https://linkedin.com"};
export const SUCCESS="success";
export const SUCCESS_MSG="Success!";
export const TOKEN_EXPIRE="Your session has expired. Please log in again.";
export const TRUE="true";
export const WARNING="warning";
export const WE_ARE_WORKING="We are working on it.";
export const LOGOUT_SUCCESS="Logout successfull"